### ISSUE TITLE
UTF-8 e quais os dicionários a alterar?

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/portuguese-pos-dict#10]
Olá, @susanaboatto e @p-goulart 

Quero melhorar os dicionários PT (ficheiros .AFF) usando algumas regras do pt-BR para os verbos, como, por exemplo: “referimo-nos”.

Aquilo tem carradas de dicionários, qual devo alterar?

Podem-me adicionar como membro deste repositório?

Outra questão: porquê os dicionários estão em ISO e não em UTF-8?

Obrigado!

![dicionarios_varios_20231216](https://github.com/languagetool-org/portuguese-pos-dict/assets/5192600/2bec260a-7ee2-48f7-8d01-0fff62a60043)

**Comment by p-goulart** [comment]
The answer about the encoding is in the documentation itself: `unmunch` does not work well with `UTF-8`.

For `pt-PT`, there are **two** dictionaries: `pt-PT-90` and `pt-PT-45`. Both must be edited.
