### ISSUE TITLE
"email" with no hyphen is also correct

### ISSUE THREAD

**Issue by dserodio** [languagetool-org/portuguese-pos-dict#27]
"e-mail" can also be written with no hyphen, as you can see by searching for `email site:uol.com.br`or `email site:folha.com.br`, for instance, and it's also recognized by Priberam: https://dicionario.priberam.org/email

However, LanguageTool flags "e-mail" as an error.

I'd love to submit a PR to fix this if someone can point me in the right direction.

Thanks!

**Comment by p-goulart** [comment]
@dserodio, indeed, the unhyphenated variant is widespread in usage and accepted by *a minority* of dictionaries. That being said, the Brazilian Academy of Letters has adjuticated in favour of _e-mail_. The _Vocabulário Ortográfico da Língua Portuguese_ continues to recommend only the form **with** the hyphen. From a strictly prescriptive point of view, the form _email_ is non-standard.

We believe our speller should show users word forms that are to be considered correct in as many situations as possible. It is perfectly conceivable, in some contexts, that someone writing _email_ will be told off for not adhering to the orthographic strictures imposed by the Academy.

---

That being said, I am personally also not very fond of this rule for a number of reasons.

@susanaboatto what do you think of accepting both hyphenated and unhyphenated forms in the **base** dictionary and having a picky/formal rule that enforces _e-mail_? That way most everyday writing shouldn't be affected, but we'd still have a safeguard for stuffier registers.

**Comment by dserodio** [comment]
> accepting both hyphenated and unhyphenated forms in the **base** dictionary and having a picky/formal rule that enforces _e-mail_? That way most everyday writing shouldn't be affected, but we'd still have a safeguard for stuffier registers.

This seems like a great solution

**Comment by susanaboatto** [comment]
> @susanaboatto what do you think of accepting both hyphenated and unhyphenated forms in the base dictionary and having a picky/formal rule that enforces e-mail? That way most everyday writing shouldn't be affected, but we'd still have a safeguard for stuffier registers.

I agree this should be the way to go.

**Comment by p-goulart** [comment]
@susanaboatto what should the specs for the rule be?

I'm thinking `formal+academic` TTs but `picky=false`. Does that make sense? Or maybe given the limited reach of the WGs for some LT clients, maybe `picky=on`?

**Comment by susanaboatto** [comment]
It would probably be best to make it `picky` in the `grammar.xml` file. I assume many people writing in a professional, but laid-back setting would appreciate having this flagged. To be honest, the _ideal_ solution would be a user option, but I suppose this is not on the books for the near future - so picky it is.
