### ISSUE TITLE
Improve prefixation of FPs

### ISSUE THREAD

**Issue by p-goulart** [languagetool-org/portuguese-pos-dict#29]
Some of these might be iffy. E.g., I'm pretty sure `autoditada` is a typo for `autodidata`. `Autotune` is also not a prefixation of `tune`, it is a full on loanword.

```
Autodescritos
reimigrando
reindicados
reintensificar
remissionem
repasseado
repressurizar
requeixo
Autoditada
Recopa
autocomplementar
autoconcebida
autodesignar
autoencontro
autoengano
autoimolaram
autoimolou
autoisentam
autolesionam
automanufatura
autoprovocada
autopunindo
autotune
reajeitou
reassinalados
recoletou
recomissionado
recongelado
redesenvolvida
redirigido
reencomendado
reestreou
```

Also these. Tokenisation issues following from lack of productive affixation in POS tagger as of dict `v0.15`. Once `jogar`, `processar`, etc. have the prefixes, the whole verb should be tokenised as expected.
```
rejogá
reprocessá
recertificá
reembalá
```

**Comment by susanaboatto** [comment]
We can probably leave `autoditada` and `autotune` out of the dictionary update

**Comment by p-goulart** [comment]
Not added:
- `repassear` (assuming a typo for valid `repassar`)
