### ISSUE TITLE
contractions

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/portuguese-pos-dict#3]
I have created new POS tags for contractions. 

See: https://github.com/languagetool-org/portuguese-pos-dict/commit/55cc9264aa5d399cf3a5d982235aec701ff652be
The full file: https://github.com/languagetool-org/portuguese-pos-dict/blob/main/src-dict/resta-lt.txt

The char '+' has been replaced with ':' because '+' is problematic for regular expressions (in synthesis). 

Does it look complete? @marcoagpinto

**Comment by marcoagpinto** [comment]
Yes, it looks complete, but I have one suggestion:
```
#fê-lo fê:lo V:PP
#fê-los fê:los V:PP
```

Can it use V:PPS for singular and V:PPP for plural, or something like that?

Thanks!

**Comment by marcoagpinto** [comment]
And we need gender too.

**Comment by marcoagpinto** [comment]
As I said, it gives a ton of hard work, but it is useful 🙂

**Comment by p-goulart** [comment]
Doesn't appear relevant as of Jan 2024, I'm closing. @marcoagpinto we *do* need a decision about pronoun+pronoun contractions in `pt-PT`, though, maybe in a separate issue.
